import { STORE_URL } from './config.mjs';
const icons = {
 arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>', download: '<path d="M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5"/>', star: '<path d="m12 3 2.8 5.8 6.4.9-4.6 4.5 1.1 6.3-5.7-3-5.7 3 1.1-6.3L2.8 9.7l6.4-.9Z"/>', grid: '<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M12 4v16M4 12h16"/>', settings: '<path d="M5 7h14M5 17h14"/><circle cx="9" cy="7" r="2.5" fill="currentColor"/><circle cx="15" cy="17" r="2.5" fill="currentColor"/>', sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>', pause: '<path d="M9 5v14M15 5v14"/>', plus: '<path d="M12 5v14M5 12h14"/>',
};
const svg = (name) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
const escape = text => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
export function page(c, lang) {
 const installHref = STORE_URL || '#install';
 const installAttributes = STORE_URL ? ' target="_blank" rel="noopener noreferrer"' : '';
 const installLabel = STORE_URL ? c.primary : lang === 'en' ? 'Coming to Chrome soon' : 'Chrome 商店版即将上线';
 const storeLink = STORE_URL ? `<a class="button primary" href="${STORE_URL}" target="_blank" rel="noopener noreferrer">${c.primary}${svg('arrow')}</a>` : `<span class="button coming-soon" aria-disabled="true">${lang==='en'?'Coming to Chrome soon':'Chrome 商店版即将上线'}</span>`;
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>${c.title}</title><meta name="description" content="${c.description}"><link rel="canonical" href="https://shadertab.simonwong.cn${c.home}"><link rel="alternate" hreflang="zh-CN" href="https://shadertab.simonwong.cn/"><link rel="alternate" hreflang="en" href="https://shadertab.simonwong.cn/en/"><link rel="alternate" hreflang="x-default" href="https://shadertab.simonwong.cn/en/"><meta property="og:type" content="website"><meta property="og:title" content="${c.title}"><meta property="og:description" content="${c.description}"><meta property="og:image" content="https://shadertab.simonwong.cn/images/promo.png"><meta property="og:url" content="https://shadertab.simonwong.cn${c.home}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/png" sizes="32x32" href="/icon/32.png"><link rel="stylesheet" href="/styles.css"><script type="module" src="/main.ts"></script></head><body>
 <a class="skip" href="#main">${lang==='en'?'Skip to content':'跳到正文'}</a>
 <header class="site-header wrap"><a class="brand" href="${c.home}" aria-label="Shader Tab"><img src="/icon/128.png" width="32" height="32" alt=""><span>Shader Tab<span class="brand-dot">·</span></span></a><nav aria-label="${lang==='en'?'Main navigation':'主导航'}"><a href="#effects">${c.navEffects}</a><a href="#details">${c.navDetails}</a><a href="#install">${c.navHelp}</a></nav><div class="header-end"><a class="language" href="${c.otherLanguage}" lang="${lang==='en'?'zh-CN':'en'}">${c.otherName}</a><a class="header-cta" href="${installHref}"${installAttributes}>${c.navDownload}${svg('arrow')}</a></div></header>
 <main id="main"><section class="hero wrap"><div class="hero-intro"><p class="eyebrow"><span></span>${c.eyebrow}</p><h1>${c.heading}</h1><p class="hero-copy">${c.intro}</p><div class="hero-actions"><a class="button primary" href="${installHref}"${installAttributes}>${installLabel}${svg('arrow')}</a><a class="text-link" href="#effects">${c.secondary}</a></div><p class="version">${c.version}</p></div><div class="hero-aside" aria-hidden="true"><div class="pixel-mark"><span></span><i></i><i></i><i></i></div><span>LIGHT<br>PIXELS<br>SPACE</span></div></section>
 <section class="experience wrap" id="effects" aria-labelledby="scene-title"><div class="section-top"><h2 id="scene-title">${c.scene}</h2><span class="live-label"><i></i><span id="live-label" aria-live="polite">${c.live}</span></span></div><div class="preview-shell" id="preview-shell"><div class="preview-stage" id="preview-stage" data-effect="grain-gradient" role="group" aria-label="Grain Gradient"><div id="shader" aria-hidden="true"></div><div class="preview-top"><span class="preview-caption">${c.demoTitle}</span><div class="preview-options"><button id="theme-toggle" aria-label="${c.theme}" title="${c.theme}">${svg('sun')}<span>${c.day}</span></button><button id="motion-toggle" aria-label="${c.pause}" title="${c.pause}" aria-pressed="false">${svg('pause')}</button></div></div><div class="preview-center" aria-hidden="true"><span class="preview-number">01</span></div><div class="preview-bottom"><button class="preview-settings" id="demo-settings" aria-label="${c.demoSettings}">${svg('settings')}</button><div class="preview-dock"><button id="demo-favorites" aria-label="${c.demoBookmarks}" aria-expanded="false">${svg('star')}</button><button id="demo-grid" aria-label="${c.demoBookmarks}" aria-expanded="false">${svg('grid')}</button></div><a class="preview-source" id="effect-source" href="https://shaders.paper.design/grain-gradient" target="_blank" rel="noopener noreferrer" title="${c.source}">Paper Shaders</a></div><div id="demo-popover" class="demo-popover" hidden><strong>${c.demoBookmarks}</strong><div><span>W</span><span>◎</span><span>R</span></div><p>${c.demoHint}</p></div></div></div><div class="effect-picker" role="group" aria-label="${c.effectGroup}">${[['grain-gradient','Grain Gradient'],['dithering','Dithering'],['pixel-blast','Pixel Field'],['data-pixel-arc','Predictive Arc'],['crt-terminal','CRT'],['shader-gradient','Shader Gradient']].map(([id,name],i)=>`<button data-effect="${id}" aria-pressed="${i===0}"><span class="effect-index">0${i+1}</span>${name}</button>`).join('')}</div><p class="preview-hint">${c.try}<span>↗</span></p></section>
 <section class="facts wrap" aria-label="${lang==='en'?'At a glance':'一览'}">${c.facts.map(([number,label])=>`<div><strong>${number}</strong><span>${label}</span></div>`).join('')}<span class="facts-note">MADE FOR<br>YOUR EVERYDAY.</span></section>
 <section id="details" class="details wrap"><p class="eyebrow">${c.detailLabel}</p><h2 class="section-title">${c.detailTitle}</h2><div class="features">${c.features.map(([number,title,body,kind])=>`<article class="feature ${kind}"><div class="feature-art" aria-hidden="true">${kind==='bookmarks'?'<div class="mini-folder"><span></span><span></span><span></span></div><div class="mini-bookmarks"><b>W</b><b>◎</b><b>R</b></div>':kind==='motion'?'<div class="motion-orb"></div><div class="motion-pixels"><i></i><i></i><i></i></div>':'<div class="privacy-symbol"><span></span></div><small>LOCAL, BY DESIGN.</small>'}</div><div class="feature-copy"><span class="section-number">${number}</span><h3>${title}</h3><p>${body}</p></div></article>`).join('')}</div></section>
 <section class="install wrap" id="install"><div class="install-intro"><p class="eyebrow">${c.installLabel}</p><h2 class="section-title">${c.installTitle}</h2><p>${STORE_URL ? c.installIntro : lang==='en'?'The Chrome Web Store listing is in preparation. There is no public install link yet.':'Chrome 商店条目准备中，正式安装入口将放在这里。'}</p>${storeLink}<small>${c.size}</small></div><div class="steps">${c.installSteps.map(([title,body],i)=>`<article><span>0${i+1}</span><div><h3>${title}</h3><p>${escape(body).replace('chrome://extensions','<code>chrome://extensions</code>')}</p></div></article>`).join('')}<p class="update-note">${c.update}</p></div></section>
 <section class="faq wrap" id="faq"><h2 class="section-title">${c.faqTitle}</h2><div>${c.faq.map(([q,a])=>`<details><summary>${q}${svg('plus')}</summary><p>${a}</p></details>`).join('')}</div></section>
 <section class="closing wrap"><img src="/icon/128.png" width="64" height="64" alt=""><h2>${c.closing}</h2><a href="${installHref}"${installAttributes} class="text-link">${installLabel}${svg('arrow')}</a></section></main>
 <footer class="site-footer wrap"><div><a class="brand" href="${c.home}">Shader Tab</a><p>${c.footerNote}</p><small>${c.copyright}</small></div><nav aria-label="${lang==='en'?'Legal and support':'政策与支持'}"><a href="${c.legalPrivacy}">${c.privacy}</a><a href="${c.legalLicenses}">${c.licenses}</a><a href="mailto:support@simonwong.cn">${c.contact}${svg('arrow')}</a></nav></footer></body></html>`;
}
